package_rename_config:
  android:
    app_name: "Guava Wallet"
    package_name: finance.guava
    # override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    # lang: # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: "Guava Wallet"
    bundle_name: finance.guava
    package_name: finance.guava

  # linux:
  #   app_name: # (String) The window title of the linux app
  #   package_name: # (String) The application id of the linux app
  #   exe_name: # (String) The executable name (binary name) of the linux app

  # macos:
  #   app_name: # (String) The product name of the macos app
  #   package_name: # (String) The product bundle identifier of the macos app
  #   copyright_notice: # (String) The product copyright of the macos app

  web:
    app_name: "Guava Wallet"
    short_app_name: GuavaFi
    description: "Guava Finance is a USDC backed CrossBorder App for Inividuals and SMEs"

  # windows:
  #   app_name: # (String) The window title & software name of the windows app
  #   organization: # (String) The organization name (company name) of the windows app
  #   copyright_notice: # (String) The legal copyright of the windows app
  #   exe_name: # (String) The executable name (binary name) of the windows app